In [19]:
from read_alignment import readAlignment
import helperFxns_new as kim_helper
import numpy as np
import pandas as pd


In [20]:
arr_seq = readAlignment('data/ProteinMPNN_sequences.txt')
arr_seq[:3]

[">cleaned, score=2.1814, fixed_chains=[], designed_chains=['A'], model_name=vanilla—v_48_020\n", 'PIRRGAIRVFVNSAFNFFIMFTIFSNCIFMTISNPPAWSKIVEYTFTGIYTFEVIVKVLSRGFCIGHFTFLRDPWNWLDFSVVTMTYITEFRTFRVLRALKTITIFPGLKTIVRALIESMKQMGDVVILTVFSLAVFTLAGMQLFMGNLRHKCIRWPISNVTLDYESAYNTTFDFTAYIENEENQYFLDGALDALLCGNNSDAGKCPEGYTCMKAGRNPNYGYTNYDNFAWTFLCLFRLMLQDYWENLYQMTLRAAGKSYMVFFIMVIFLGSFYLINLILAVVAMAYEEQNQATLAEAQEKEAEFQRAVEQLRNCCGPWVFLKKWVHFVMMDPFTDLFITLCIILNTLFMSIEHHPMNESFQSLLSAGNLVFTTIFAAEMVLKIIALDPYYYFQQTWNIFDSIIVSLSLLELGLSGMSVLRSLRLLRIFKLAKSWPTLNILIKIICNSVGALGNLTIVLAIIVFIFALVGFQLFGKNYKEYVCKISDDCELPRWHMNDFFHSFLIVFRALCGEWIETMWDCMEVGGVPMCLAVYMMVIIIGNLVMLNLFLALLLSSFGKIWWNLRRTCYTIVEHDYFETFIIFMILLSSGVLAFEDIYIWRRRVIKVILEYADKVFTYVFIVEMLLKWVAYGFKRYFTDAWCWLDFVIVGASIMGITSSLIKNLRTIRALRPLRALSRFEGMKVVVRALLGAIPSIMNVLLVCLMFWLIFSIMGVNLFAGKFYRCINTTTDEILPVEEVNNRSDCMALMYTNEVRWVNLKVNYDNAGMGYLSLLQVSTFKGWMDIMYAAVDSREVEDQPIYEINVYMYLYFVIFIVFGAFFTLNLFIGVIIDNFNRQKQKLGGEDLFMTEEQKKYYNAMKKLGSKKAAKCIPRPSNVVQGVVYDIVTQPFTDIFIMALICI

['PIRRGAIRVFVNSAFNFFIMFTIFSNCIFMTISNPPAWSKIVEYTFTGIYTFEVIVKVLSRGFCIGHFTFLRDPWNWLDFSVVTMTYITEFRTFRVLRALKTITIFPGLKTIVRALIESMKQMGDVVILTVFSLAVFTLAGMQLFMGNLRHKCIRWPISNVTLDYESAYNTTFDFTAYIENEENQYFLDGALDALLCGNNSDAGKCPEGYTCMKAGRNPNYGYTNYDNFAWTFLCLFRLMLQDYWENLYQMTLRAAGKSYMVFFIMVIFLGSFYLINLILAVVAMAYEEQNQATLAEAQEKEAEFQRAVEQLRNCCGPWVFLKKWVHFVMMDPFTDLFITLCIILNTLFMSIEHHPMNESFQSLLSAGNLVFTTIFAAEMVLKIIALDPYYYFQQTWNIFDSIIVSLSLLELGLSGMSVLRSLRLLRIFKLAKSWPTLNILIKIICNSVGALGNLTIVLAIIVFIFALVGFQLFGKNYKEYVCKISDDCELPRWHMNDFFHSFLIVFRALCGEWIETMWDCMEVGGVPMCLAVYMMVIIIGNLVMLNLFLALLLSSFGKIWWNLRRTCYTIVEHDYFETFIIFMILLSSGVLAFEDIYIWRRRVIKVILEYADKVFTYVFIVEMLLKWVAYGFKRYFTDAWCWLDFVIVGASIMGITSSLIKNLRTIRALRPLRALSRFEGMKVVVRALLGAIPSIMNVLLVCLMFWLIFSIMGVNLFAGKFYRCINTTTDEILPVEEVNNRSDCMALMYTNEVRWVNLKVNYDNAGMGYLSLLQVSTFKGWMDIMYAAVDSREVEDQPIYEINVYMYLYFVIFIVFGAFFTLNLFIGVIIDNFNRQKQKLGGEDLFMTEEQKKYYNAMKKLGSKKAAKCIPRPSNVVQGVVYDIVTQPFTDIFIMALICINMVAMMVESEDQSQVKKDILSQINVIFVIIFTVECLLKLLALRQYFFTVGWNVFDFAVVVISIIGLLLSDIISPTLFRVIRLARIARVLRLIRAAKG

In [21]:
arr_seq[0]

'PIRRGAIRVFVNSAFNFFIMFTIFSNCIFMTISNPPAWSKIVEYTFTGIYTFEVIVKVLSRGFCIGHFTFLRDPWNWLDFSVVTMTYITEFRTFRVLRALKTITIFPGLKTIVRALIESMKQMGDVVILTVFSLAVFTLAGMQLFMGNLRHKCIRWPISNVTLDYESAYNTTFDFTAYIENEENQYFLDGALDALLCGNNSDAGKCPEGYTCMKAGRNPNYGYTNYDNFAWTFLCLFRLMLQDYWENLYQMTLRAAGKSYMVFFIMVIFLGSFYLINLILAVVAMAYEEQNQATLAEAQEKEAEFQRAVEQLRNCCGPWVFLKKWVHFVMMDPFTDLFITLCIILNTLFMSIEHHPMNESFQSLLSAGNLVFTTIFAAEMVLKIIALDPYYYFQQTWNIFDSIIVSLSLLELGLSGMSVLRSLRLLRIFKLAKSWPTLNILIKIICNSVGALGNLTIVLAIIVFIFALVGFQLFGKNYKEYVCKISDDCELPRWHMNDFFHSFLIVFRALCGEWIETMWDCMEVGGVPMCLAVYMMVIIIGNLVMLNLFLALLLSSFGKIWWNLRRTCYTIVEHDYFETFIIFMILLSSGVLAFEDIYIWRRRVIKVILEYADKVFTYVFIVEMLLKWVAYGFKRYFTDAWCWLDFVIVGASIMGITSSLIKNLRTIRALRPLRALSRFEGMKVVVRALLGAIPSIMNVLLVCLMFWLIFSIMGVNLFAGKFYRCINTTTDEILPVEEVNNRSDCMALMYTNEVRWVNLKVNYDNAGMGYLSLLQVSTFKGWMDIMYAAVDSREVEDQPIYEINVYMYLYFVIFIVFGAFFTLNLFIGVIIDNFNRQKQKLGGEDLFMTEEQKKYYNAMKKLGSKKAAKCIPRPSNVVQGVVYDIVTQPFTDIFIMALICINMVAMMVESEDQSQVKKDILSQINVIFVIIFTVECLLKLLALRQYFFTVGWNVFDFAVVVISIIGLLLSDIISPTLFRVIRLARIARVLRLIRAAKGI

In [22]:
# convert from array of string seq to numeric
arr_num = kim_helper.lett2num(arr_seq, code='ACDEFGHIKLMNPQRSTVWY-')
arr_num

array([[13,  8, 15, ...,  4, 16, 16],
       [ 6,  5, 21, ..., 15, 15, 10],
       [ 6, 10, 15, ..., 10, 15,  9],
       ...,
       [ 6, 10, 15, ...,  9, 15,  5],
       [ 6, 10, 15, ..., 15, 15, 15],
       [ 6, 10, 15, ..., 15, 10, 15]])

In [24]:
arr_num[1,:][:10]

array([ 6,  5, 21, 21, 21,  5,  9,  9,  8, 20])

In [12]:
# convert to one-hot encoding
one_hot = kim_helper.alg2bin(arr_num)
one_hot

<81x23940 sparse matrix of type '<class 'numpy.float64'>'
	with 92340 stored elements in Compressed Sparse Row format>

In [13]:
print('array num shape:', arr_num.shape)
print('one hot shape:', one_hot.shape)

array num shape: (81, 1140)
one hot shape: (81, 23940)


In [14]:
# header, seq = kim_helper.filterAln(one_hot, arr_num)
hd = np.arange(0, len(arr_num))
hFilt, seqFilt = kim_helper.filterAln_iaj(hd, arr_num)

In [18]:
seqFilt.shape

(81, 1140)

In [15]:
np_arr_num = np.array(arr_num)
np_arr_num.shape

(81, 1140)

In [7]:
np.unique(np_arr_num)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
np_arr_num[:, -1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
len(hFilt)
len(seqFilt[0])

1140

In [8]:
seq_test = arr_num[0]
seq_test

array([13,  8, 15, ..., 16, 16,  0])

In [9]:
len(arr_num)

81

In [10]:
np.sum(seq_test == 0,axis=0)
# np.unique(seq_test)

1

In [11]:
len(header)
header[0].shape
seq.shape

NameError: name 'header' is not defined